"use client";

import React, { useState } from "react";
import { fetchAIExplanation, AIExplainResponse } from "../lib/api";

interface LocalAIExplanationCardProps {
  caseId: string;
  className?: string;
}

export function LocalAIExplanationCard({ caseId, className }: LocalAIExplanationCardProps) {
  const [explanation, setExplanation] = useState<AIExplainResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [audienceMode, setAudienceMode] = useState<"simple" | "auditor">("simple");
  const [engineMode, setEngineMode] = useState<"llm" | "deterministic">("llm");
  const [currentStyle, setCurrentStyle] = useState<"standard" | "concise" | "breakdown">("standard");

  async function handleGenerate(styleToUse: "standard" | "concise" | "breakdown" = currentStyle) {
    setLoading(true);
    setError(null);
    try {
      const data = await fetchAIExplanation(caseId, styleToUse);
      if (data) {
        setExplanation(data);
        setCurrentStyle(styleToUse);
      } else {
        setError("AI Assistant currently unavailable. Using deterministic evidence briefing.");
      }
    } catch {
      setError("AI service offline. Core financial engine remains 100% operational.");
    } finally {
      setLoading(false);
    }
  }

  function getActiveText(): string {
    if (!explanation) return "";
    if (engineMode === "deterministic") {
      return audienceMode === "simple"
        ? (explanation.simple_narrative || explanation.economic_story || explanation.narrative || "")
        : (explanation.auditor_narrative || explanation.deterministic_narrative || explanation.narrative || "");
    }
    // LLM mode: narrative is dynamically generated by Ollama
    if (audienceMode === "simple") {
      return explanation.narrative || explanation.simple_narrative || "";
    }
    return explanation.auditor_narrative || explanation.narrative || "";
  }

  function handleCopy() {
    const text = getActiveText();
    if (text) {
      navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }

  function handleRegenerateNext() {
    const nextStyle = currentStyle === "standard" ? "concise" : currentStyle === "concise" ? "breakdown" : "standard";
    handleGenerate(nextStyle);
  }

  const activeText = getActiveText();

  return (
    <div className={`bg-white border border-[#e7e2d9] rounded-2xl p-6 space-y-4 shadow-xs ${className || ""}`}>
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-stone-100 pb-3 gap-2">
        <div className="flex items-center space-x-2">
          <span className="w-2.5 h-2.5 rounded-full bg-cyan-500 animate-pulse"></span>
          <h3 className="text-sm font-bold text-stone-900 font-sans">
            AI Narrative Investigation Assistant
          </h3>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <span className="text-[10px] uppercase font-mono px-2 py-0.5 rounded-full bg-cyan-50 text-cyan-800 border border-cyan-200">
            {explanation?.provider === "local_llm_ollama"
              ? "🦙 Ollama Local LLM (llama3.2)"
              : "⚡ Deterministic Grounding Core"}
          </span>
        </div>
      </div>

      {/* Safety & Bounding Notice */}
      <div className="p-3 rounded-xl bg-[#f0fdf4] border border-[#86efac] text-xs text-[#14532d] flex items-center space-x-2">
        <span>🛡️</span>
        <span className="font-medium">
          <strong>Non-Authoritative Explainer:</strong> AI explains the evidence. It does not decide the financial outcome.
        </span>
      </div>

      {!explanation ? (
        <div className="p-6 text-center bg-[#faf8f5] rounded-xl border border-[#e7e2d9] space-y-3">
          <p className="text-stone-600 text-xs max-w-md mx-auto">
            Generate an evidence-grounded audit narrative explaining this discrepancy, candidate economic hypothesis, and decision rationale.
          </p>
          <button
            onClick={() => handleGenerate("standard")}
            disabled={loading}
            className="px-5 py-2.5 bg-stone-900 hover:bg-stone-800 text-white font-bold text-xs rounded-xl uppercase tracking-wider transition shadow-sm"
          >
            {loading ? "Generating Plain-English Briefing via Ollama..." : "✨ Generate AI Investigation Narrative"}
          </button>
          {error && <p className="text-xs text-amber-700 font-medium">{error}</p>}
        </div>
      ) : (
        <div className="space-y-4">
          {/* Audience & Engine Controls */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 p-2 bg-[#faf8f5] rounded-xl border border-[#e2ddd5]">
            {/* Audience Toggle */}
            <div className="flex items-center space-x-1">
              <span className="text-[10px] font-bold uppercase text-stone-400 mr-1 hidden sm:inline">
                Audience:
              </span>
              <button
                onClick={() => setAudienceMode("simple")}
                className={`px-3 py-1 rounded-lg text-xs font-semibold transition ${
                  audienceMode === "simple"
                    ? "bg-white text-stone-900 shadow-2xs font-bold border border-stone-300"
                    : "text-stone-500 hover:text-stone-800"
                }`}
              >
                👶 Simple Story (ELIF5)
              </button>
              <button
                onClick={() => setAudienceMode("auditor")}
                className={`px-3 py-1 rounded-lg text-xs font-semibold transition ${
                  audienceMode === "auditor"
                    ? "bg-white text-stone-900 shadow-2xs font-bold border border-stone-300"
                    : "text-stone-500 hover:text-stone-800"
                }`}
              >
                📋 Auditor Briefing (Technical)
              </button>
            </div>

            {/* Engine Toggle */}
            <div className="flex items-center space-x-1">
              <span className="text-[10px] font-bold uppercase text-stone-400 mr-1 hidden sm:inline">
                Model:
              </span>
              <button
                onClick={() => setEngineMode("llm")}
                className={`px-2.5 py-1 rounded-lg text-xs font-semibold transition ${
                  engineMode === "llm"
                    ? "bg-purple-50 text-purple-900 font-bold border border-purple-200 shadow-2xs"
                    : "text-stone-500 hover:text-stone-800"
                }`}
              >
                🦙 Ollama
              </button>
              <button
                onClick={() => setEngineMode("deterministic")}
                className={`px-2.5 py-1 rounded-lg text-xs font-semibold transition ${
                  engineMode === "deterministic"
                    ? "bg-emerald-50 text-emerald-900 font-bold border border-emerald-200 shadow-2xs"
                    : "text-stone-500 hover:text-stone-800"
                }`}
              >
                ⚡ Deterministic
              </button>
            </div>
          </div>

          {/* Headline */}
          <div className="p-3.5 bg-[#f0f9ff] border border-[#7dd3fc] rounded-xl text-[#0369a1] font-bold text-sm font-sans">
            {explanation.headline}
          </div>

          {/* Narrative Content */}
          <div className="p-4 bg-[#faf8f5] rounded-xl border border-[#e7e2d9] text-stone-800 leading-relaxed whitespace-pre-line text-xs font-sans">
            {activeText}
          </div>

          {/* Action Bar */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between pt-1 gap-2 text-xs">
            <div className="flex items-center space-x-2 text-[11px] text-stone-500 font-sans">
              <span>Zero hallucination risk &bull; Strictly bounded by structured engine facts</span>
              {currentStyle !== "standard" && (
                <span className="px-2 py-0.5 rounded-full bg-purple-100 text-purple-800 text-[10px] font-mono border border-purple-200 uppercase">
                  Style: {currentStyle}
                </span>
              )}
            </div>
            <div className="flex items-center space-x-2">
              <button
                onClick={handleCopy}
                className="px-3 py-1.5 bg-stone-100 hover:bg-stone-200 text-stone-800 rounded-lg text-xs font-semibold border border-stone-300 transition"
              >
                {copied ? "✓ Copied" : "Copy Briefing"}
              </button>
              <button
                onClick={handleRegenerateNext}
                disabled={loading}
                className="px-3 py-1.5 bg-purple-50 hover:bg-purple-100 text-purple-900 rounded-lg text-xs font-semibold border border-purple-300 transition flex items-center space-x-1"
                title="Cycles through standard, concise, and detailed breakdown phrasings"
              >
                <span>🔄</span>
                <span>{loading ? "Regenerating..." : "Regenerate (Simpler Phrasing)"}</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
